feature/smartrating_actions
salute-developers/smart_app_framework pull request #12
Opened 2022-04-29 07:37 UTC by Dan1lD

2022-05-05 20:50 UTC, SyrexMinus commented
Добавь доку на акшны.

2022-05-05 20:53 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +            "kafka_key": "main",
Мб сделать это поле кастомизируемым? В конфиге можно использовать и не main.

2022-05-05 20:53 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +            "kafka_key": "main",
Мб сделать это поле кастомизируемым? В конфиге можно использовать и не main.

2022-05-05 20:54 UTC, SyrexMinus requested changes
добавь доку и подумай над кастомизацией `kafka_key`

2022-05-16 06:47 UTC, bart0003 commented on core/basic_models/actions/smartrating.py
> +    DEFAULT_KAFKA_KEY = "main"
?

2022-05-16 06:53 UTC, bart0003 commented on core/basic_models/actions/smartrating.py
> +            "kafka_replyTopic": user.settings["template_settings"]["consumer_topic"]
consumer_topic прокинуть из Kafka-config

2022-05-16 09:07 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +        self.kafka_key = items.get("kafka_key")
Дублируется здесь и в CallRatingAction, можно добавить эту строчку в SmartRatingAction в инит.

2022-05-16 09:09 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +class CallRatingAction(SmartRatingAction):
Добавь доку к классу, как в SmartPayCreateAction

2022-05-16 09:09 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +class AskRatingAction(SmartRatingAction):
Добавь доку к классу, как в SmartPayCreateAction

2022-05-16 09:20 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +                user.settings["kafka"]["template-engine"]["main"]["consumer"]["topics"]["smartrating"]
Поправь путь, добавив kafka_key такой же как и строчкой выше. "main" - это kafka_key.

2022-05-16 09:21 UTC, SyrexMinus commented
Комментарии к описанию ПРа: 
1. "Example::" лучше выносить за пределы кавычек кода, потому что это не код.
2. В kafka_config необходимо задать kafka_replyTopic в smartrating -> kafka_replyTopic задаётся в конфиге Kafka в template-engine.<kafka_key>.consumer.topics.smartrating

2022-05-16 09:22 UTC, SyrexMinus requested changes
Порефактори и поменяй описание.

2022-05-19 11:32 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    """Отправляет 'CALL_RATING' в SmartRating API
```suggestion
    """Отправляет 'CALL_RATING' в SmartRating API
    
```

2022-05-19 11:35 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    https://confluence.sberbank.ru/display/SDAT/API+SmartRating
Ссылку не смогут открыть внешние разработчики, поэтому лучше либо впилить сюда описание акшна, либо найти доступную ссылку для внешних разрабов. И добавь мини-дескрипшн к ссылке, типа "Описание: https://link.com/call_rating"

2022-05-19 11:35 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    """Отправляет 'ASK_RATING' в SmartRating API
```suggestion
    """Отправляет 'ASK_RATING' в SmartRating API
    
```

2022-05-19 11:37 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +            "kafka_key": "some_key" // опциональный параметр, по умолчанию "main"
Опиши что это за параметр

2022-05-19 11:38 UTC, SyrexMinus requested changes
докстринги надо бы поправить

2022-05-20 13:26 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    """Отправляет 'CALL_RATING' в SmartRating API
```suggestion
    """Action запроса оценки смартапа у пользователя через SmartRating API
```

2022-05-20 13:54 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    Документация для внутренних разработчиков: https://confluence.sberbank.ru/display/SMDG/API+SmartRating
```suggestion
    Документация, доступная для внутренних разработчиков: https://confluence.sberbank.ru/display/SMDG/API+SmartRating
```

2022-05-20 13:55 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    """Action запроса оценки смартапа у пользователя через SmartRating API
```suggestion
    """Action запроса оценки смартапа у пользователя по его инициативе через SmartRating API
```

2022-05-20 13:55 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +    """Отправляет 'ASK_RATING' в SmartRating API
```suggestion
    """Action запроса оценки смартапа у пользователя без его инициативы через SmartRating API
```

2022-05-20 13:58 UTC, SyrexMinus approved these changes

2022-05-20 14:14 UTC, SyrexMinus commented on core/basic_models/actions/smartrating.py
> +        self.request_data = {
должен быть пустой дикт для хттп

2023-11-15 12:35 UTC, SyrexMinus approved these changes

2023-11-16 10:11 UTC, DimaProskurin commented
Я бы закрыл этот PR как невостребованный. Если мы это вольем, то этим никто не будет пользоваться, никто не протестирует E2E. Будет у нас просто лежать, а мы даже не будем знать работает ли оно как надо

2023-11-20 09:34 UTC, closed without merging