feature/init_handlers
salute-developers/smart_app_framework pull request #15
Opened 2022-05-13 12:09 UTC by Dan1lD

Добавляет возможность использовать кастомные хэндлеры в плагинах без написания кастомной `SmartAppModel`

Пример:
```python3
from smart_kit.models.smartapp_model import additional_handlers as plugin_handlers

def on_startup(app_config: ModuleType, manager: AppManager) -> None:
    plugin_handlers["DDP_RS"] = HandlerDdp
```

2022-05-13 12:14 UTC, dangerink approved these changes

2022-05-13 15:40 UTC, bart0003 commented on smart_kit/models/smartapp_model.py
> +            message_name: handler(self.app_name) for message_name, handler in additional_handlers.items()
Что такое `handler()`?

2022-05-13 15:44 UTC, bart0003 commented on smart_kit/models/smartapp_model.py
> +additional_handlers = {}
Может лучше сделать это статик полем в классе?

2022-05-13 15:47 UTC, bart0003 commented on smart_kit/models/smartapp_model.py
> +            message_name: handler(self.app_name) for message_name, handler in additional_handlers.items()
А что с хендлерами, требующими дополнительные параметры?

2022-05-13 15:48 UTC, bart0003 commented
Еще бы я где-то в доку добавил, что можно так делать

2022-05-16 06:45 UTC, bart0003 requested changes
^
 |

2022-05-16 10:53 UTC, SyrexMinus commented on smart_kit/models/smartapp_model.py
> +            message_name: handler(self.app_name) for message_name, handler in self.additional_handlers.items()
К комментарию Артёма про дополнительные аргументы:
```suggestion
            message_name: handler_params["handler"](self.app_name, **handler_params.get("params", {})) for message_name, handler_params in self.additional_handlers.items()
```
где формат `additional_handlers` примерно такой:
{"MESSAGE_TO_SKILL": {"handler": HandlerText, "params": {"dialogue_manager": self.dialogue_manager}}}

2022-05-19 09:51 UTC, bart0003 commented on smart_kit/models/smartapp_model.py
> +            message_name: handler(self.app_name) for message_name, handler in self.additional_handlers.items()
Го. @Dan1lD норм?

2022-05-19 11:39 UTC, SyrexMinus approved these changes

2022-05-19 11:46 UTC, merged