fix queue_index
salute-developers/smart_app_framework pull request #162
Opened 2023-11-08 07:55 UTC by Dan1lD

fix #98

2023-11-16 10:23 UTC, DimaProskurin requested changes

2023-11-16 10:23 UTC, DimaProskurin commented on smart_kit/start_points/main_loop_kafka.py
> +            queue_index = int(hashlib.sha1(key).hexdigest(), 16) % len(self.queues)
1. у нас есть проверка запрещающая ставить кол-во очередей меньше 1 ? Если нет, то давай добавим и будем делать raise ValueError если юзер такое вписал

2023-11-16 10:23 UTC, DimaProskurin commented on smart_kit/start_points/main_loop_kafka.py
> +            queue_index = int(hashlib.sha1(key).hexdigest(), 16) % len(self.queues)
Варнинг предлагает заменить хэшфункцию. Давай заменим на sha256

2023-11-17 09:15 UTC, Dan1lD commented on smart_kit/start_points/main_loop_kafka.py
> +            queue_index = int(hashlib.sha1(key).hexdigest(), 16) % len(self.queues)
done

2023-11-20 09:22 UTC, SyrexMinus approved these changes

2023-11-20 09:22 UTC, merged