DPNLPF-1782: Поправить форматирование и обращения в template аппе
salute-developers/smart_app_framework pull request #46
Opened 2022-09-07 21:45 UTC by SyrexMinus

Проблемы с шаблоном навыка во фреймворке: форматирование docstring'ов не соответсвует общепринятому по PEP, названия классов содержат орфографические ошибки, а в коде есть синтаксические ошибки.
Примеры ошибок:
форматирование:
```
class CustomDialogueManager(DialogueManager):
"""
В собственном DialogManager можно переопределить логику, связанную с вызовом сценариев по входяшему интенту
"""
```
орфографические ошибки: CustomeUser
синтаксические ошибки:
```
class CustomFieldFiller(FieldFillerDescription):
def _init_(self, items: Optional[Dict[str, Any]], id: Optional[str] = None) -> None:
super(SampleFieldFiller, self)._init_(items, id)
```
Надо починить для того, чтобы код был синтаксически верен и запускался и разработчики смартаппов не теряли доверие к фреймворку и продуктам Сбера, в целом.

2022-09-08 15:28 UTC, SyrexMinus commented
Проверил тесты во фреймворке, пакетный прогон в темплейт аппе, интеграцию навыка на main_loop с кабинетом разработчика (app_connector). Всё работает штатно.

2022-09-09 13:03 UTC, DimaProskurin commented
👀

2022-09-09 13:33 UTC, DimaProskurin commented on smart_kit/template/app/user/parametrizer.py-tpl
> +    """Параметризатор определяет данные, которые будут доступны в jinja-вставках в языке фреймворкаъ
"ъ" в слове "фреймворкаъ"

2022-09-09 13:38 UTC, DimaProskurin commented on smart_kit/template/app/handlers/handlers.py-tpl
> +        super().run(payload, user)
Нарушен интерфейс метода `run`. Метод `run` в классе `HandlerBase` тоже должен возвращать список команд - пусть и пустой. 
Классы наследники должны получать список команд от класса родителя и уже добавлять свои команды в полученный список. 
То есть должно быть что-то вида `commands = super().run(payload, user)`, `commands.extend(new_commands)` `return commands`

2022-09-09 13:57 UTC, SyrexMinus commented on smart_kit/template/app/user/parametrizer.py-tpl
> +    """Параметризатор определяет данные, которые будут доступны в jinja-вставках в языке фреймворкаъ
я из советского союза

2022-09-09 14:42 UTC, SyrexMinus commented on smart_kit/template/app/user/parametrizer.py-tpl
> +    """Параметризатор определяет данные, которые будут доступны в jinja-вставках в языке фреймворкаъ
Done

2022-09-09 14:43 UTC, SyrexMinus commented on smart_kit/template/app/handlers/handlers.py-tpl
> +        super().run(payload, user)
Done, в том числе для всего, что было во фреймворке. Добавил аннотации за одно.

2022-09-09 15:31 UTC, DimaProskurin commented on smart_kit/handlers/handler_base.py
> +    def run(self, payload: Dict, user: User) -> List[Command]:
`payload: Dict[str, Any]`

2022-09-09 15:41 UTC, DimaProskurin commented on smart_kit/template/app/user/parametrizer.py-tpl
> +        super().__init__(user, items)
Аналогичные рассуждения про конструктор. Тут его можно убрать

2022-09-09 15:57 UTC, DimaProskurin commented on smart_kit/template/app/adapters/db_adapters.py-tpl
> +        super().__init__(config)
С другой стороны - это класс-шаблон, и мы хотим показать юзеру, что его можно расширять, изменяя и дописывая свою логику в конструкторе класса-наследника 
Я думаю изначально именно эта цель и преследовалась и поэтому конструктор оставили в таком виде
Так что все норм =) просто немного навел суеты

2022-09-09 16:03 UTC, DimaProskurin commented on smart_kit/handlers/handler_timeout.py
> +            commands.extend(user.behaviors.timeout(callback_id))
Метод `timeout` у класса `Behaviors` вызывает `timeout_action` - что есть экземпляр класса `Action`, который согласно сигнатуре возвращает `Optional[List[Command]]`
Соответственно, если он вернет `None`, то мы упадем в месте `.extend(None)`

2022-09-09 16:11 UTC, DimaProskurin commented on smart_kit/handlers/handler_take_profile_data.py
> +            commands.extend(user.behaviors.success(user.message.callback_id))
Аналогичные рассуждения, что и выше, что можем упасть на месте `.extend(None)`

2022-09-09 16:13 UTC, DimaProskurin commented on smart_kit/handlers/handle_close_app.py
>          super(HandlerCloseApp, self).__init__(app_name)
`super().__init__(app_name)`

2022-09-09 16:15 UTC, DimaProskurin commented
Все остальное хорошо

2022-09-09 16:17 UTC, DimaProskurin commented on smart_kit/handlers/handler_timeout.py
> +            commands.extend(user.behaviors.timeout(callback_id))
Возможно стоит сделать, чтобы метод `run` у класса `Action` тоже возвращал только `List[Command]`, а не `Optional[List[Command]]` как сейчас
На подумать

2022-09-12 15:56 UTC, SyrexMinus commented on smart_kit/template/app/adapters/db_adapters.py-tpl
> +        super().__init__(config)
Зарезолви, если норм

2022-09-14 20:53 UTC, SyrexMinus commented on smart_kit/handlers/handler_base.py
> +    def run(self, payload: Dict, user: User) -> List[Command]:
Done

2022-09-14 20:54 UTC, SyrexMinus commented on smart_kit/handlers/handler_timeout.py
> +            commands.extend(user.behaviors.timeout(callback_id))
Переписал Action'ы, что они возвращают только List[Command]. То же самое для Behavior'ов.

2022-09-14 20:54 UTC, SyrexMinus commented on smart_kit/handlers/handler_take_profile_data.py
> +            commands.extend(user.behaviors.success(user.message.callback_id))
Done

2022-09-14 20:54 UTC, SyrexMinus commented on smart_kit/handlers/handle_close_app.py
>          super(HandlerCloseApp, self).__init__(app_name)
Done

2022-09-16 08:20 UTC, DimaProskurin commented on scenarios/actions/action.py
> +def clear_scenario(user, scenario_id):
Можно сделать его @staticmethod и пользоваться везде где нужно

2022-09-16 08:21 UTC, DimaProskurin commented on scenarios/actions/action.py
> +class ClearScenarioByIdAction(Action):  # wrong inheritance
Что значит коммент "# wrong inheritance"?

2022-09-16 08:22 UTC, DimaProskurin commented on scenarios/actions/action.py
> +    def run(self, user, text_preprocessing_result, params=None) -> List[Command]:
Не хватает type hints

2022-09-16 08:40 UTC, DimaProskurin commented on core/basic_models/actions/basic_actions.py
>      def build_actions(self) -> List[str]:
Думаю что должно быть `-> List[Action]`

2022-09-16 08:49 UTC, DimaProskurin commented on core/basic_models/actions/counter_actions.py
> +class CounterSetAction(CounterAction):
В `def __init__` 
`super(CounterSetAction, self).__init__(items, id)` -> `super().__init__(items, id)`

2022-09-16 08:51 UTC, DimaProskurin commented on smart_kit/handlers/handler_timeout.py
> +            return commands
`return commands` внутри `if`, а должен быть снаружи

2022-09-21 09:32 UTC, DimaProskurin requested changes
Оставил комменты

2022-09-21 15:45 UTC, SyrexMinus commented on scenarios/actions/action.py
> +def clear_scenario(user, scenario_id):
А можно оставить в виде standalone-функции :)

2022-09-21 16:04 UTC, SyrexMinus commented on smart_kit/handlers/handler_timeout.py
> +            return commands
Ты прав, Done

2022-09-21 16:04 UTC, SyrexMinus commented on core/basic_models/actions/basic_actions.py
>      def build_actions(self) -> List[str]:
Ты прав, Done

2022-09-21 16:04 UTC, SyrexMinus commented on scenarios/actions/action.py
> +    def run(self, user, text_preprocessing_result, params=None) -> List[Command]:
Done

2022-09-21 16:04 UTC, SyrexMinus commented on scenarios/actions/action.py
> +class ClearScenarioByIdAction(Action):  # wrong inheritance
Коммент для себя, убрал

2022-09-22 09:38 UTC, DimaProskurin commented on scenarios/actions/action.py
> +def clear_scenario(user, scenario_id):
Справедливо

2022-09-27 12:14 UTC, merged