DPNLPF-1714: change type of the value argument of SmartAppFromMessage to dict
salute-developers/smart_app_framework pull request #48
Opened 2022-09-08 19:57 UTC by SyrexMinus

Проблема заключается в неработоспособности тестов на DP. Причиной этого является несоответствие интерфейсов между DialogPolicyFromMessage и SmartAppFromMessage. В первом аргумент \_\_init\_\_() value имеет тип dict, а во втором используется str, который внутри декодируется в dict через json.loads(). Второй подход иногда требует лишних действий, например, если изначально ещё непереданный value уже dict, то его приходится приводить к строке json.dumps для соблюдения интерфейса. От этого действия можно избавиться, если ожидать уже готовый тип dict. Это изменение и делает данный pull request.
Более того, с точки зрения дизайна, решение с ожиданием dict позволяет избавить SmartAppFromMessage от допущения, что сырые данные, которые приходят внутри value - это json в виде строки. Таким образом, ожидая dict, сырое значение больше не ограничивается исключительно json в виде строки.

2022-09-09 09:02 UTC, DimaProskurin commented
👀

2022-09-09 09:09 UTC, DimaProskurin commented on smart_kit/testing/local.py
> +    def process_message(self, raw_message: typing.Dict, headers: tuple = ()) -> typing.Tuple[typing.Any, list]:
Давай сделаем в этом файле, как и в остальных: `from typing import Dict, Optional`, а потом где надо использовать просто `Dict`, `Optional`

2022-09-09 10:34 UTC, SyrexMinus commented on smart_kit/testing/local.py
> +    def process_message(self, raw_message: typing.Dict, headers: tuple = ()) -> typing.Tuple[typing.Any, list]:
Done

2022-09-09 11:22 UTC, DimaProskurin commented on smart_kit/testing/local.py
> +            respond = json.loads(self.after_process_message(answer))
`self.after_process_message(answer)` может вернуть `None`
Тогда `json.loads(None)` упадет

2022-09-09 11:54 UTC, DimaProskurin commented on smart_kit/utils/diff.py
> +            not (isinstance(actual, str) and isinstance(expected, str) and re.fullmatch(expected, actual)):
Если метод `partial_diff` сравнивает два произвольных объекта на равенство, то нужна только проверка `expected != actual` т.к. метод `re.fullmatch` работает только на строках. 

Если метод `partial_diff` хочет сравнить 2 строки на равенство, то проверки `expected != actual` также достаточно. Две строки в питоне можно сравнить через оператор `==`

Короче, кажется, что можно выпилить проверку `re.fullmatch(expected, actual)` совсем тут

2022-09-09 13:16 UTC, SyrexMinus commented on smart_kit/utils/diff.py
> +            not (isinstance(actual, str) and isinstance(expected, str) and re.fullmatch(expected, actual)):
re.fullmatch существует для того, чтобы в тестах можно было регулярки использовать, проблемы нет

2022-09-09 13:19 UTC, SyrexMinus commented on smart_kit/testing/local.py
> +            respond = json.loads(self.after_process_message(answer))
Done

2022-09-09 13:19 UTC, DimaProskurin commented on smart_kit/utils/diff.py
> +            not (isinstance(actual, str) and isinstance(expected, str) and re.fullmatch(expected, actual)):
Понял, тогда все норм. 
Просто в тестах не нашел, чтобы это использовали вместе с регулярками

2022-09-09 13:21 UTC, DimaProskurin approved these changes

2022-09-21 09:14 UTC, DimaProskurin commented on core/message/from_message.py
> +                print(a)
Видимо забыл удалить

2022-09-21 09:24 UTC, DimaProskurin commented on core/message/from_message.py
> +    def value(self) -> str:
я бы лучше это назвал `def as_str(self) -> str:`
иначе путаница будет: поле _value типа dict, а свойство value типа str

2022-09-21 09:25 UTC, DimaProskurin commented on core/message/from_message.py
> +                 validators: Iterable[MessageValidator] = ()):
в конце у метода `__init __` надо добавить `-> None`

2022-09-21 09:27 UTC, DimaProskurin commented on tests/core_tests/mq_test/test_from_message.py
> +        self.assertEqual(json.dumps(input_msg, ensure_ascii=False), message.value)
если сделать свойство as_str то тут надо будет поменять на message.as_str

2022-09-21 09:30 UTC, DimaProskurin requested changes
Оставил комментарии

2022-09-21 14:46 UTC, SyrexMinus commented on core/message/from_message.py
> +                 validators: Iterable[MessageValidator] = ()):
Но __init __ же не может возвращать что-то, кроме None. Какой в этом смысл?

2022-09-21 15:11 UTC, SyrexMinus commented on core/message/from_message.py
> +                print(a)
Done

2022-09-21 15:11 UTC, SyrexMinus commented on core/message/from_message.py
> +    def value(self) -> str:
Done

2022-09-21 15:11 UTC, SyrexMinus commented on core/message/from_message.py
> +    def value(self) -> str:
жалко обратную совместимость((

2022-09-21 15:11 UTC, SyrexMinus commented on tests/core_tests/mq_test/test_from_message.py
> +        self.assertEqual(json.dumps(input_msg, ensure_ascii=False), message.value)
Done

2022-09-22 09:29 UTC, DimaProskurin commented on core/message/from_message.py
> +                 validators: Iterable[MessageValidator] = ()):
Это тема спорная и полна обсуждений. Вот например https://github.com/python/mypy/issues/3358
Я не настаиваю на `-> None`
Главное чтобы было единообразно

2022-09-22 09:30 UTC, DimaProskurin approved these changes

2022-09-27 12:02 UTC, merged