DPNLPF-1791 adding mainloop type check
salute-developers/smart_app_framework pull request #55
Opened 2022-09-26 14:07 UTC by DenisSivko

DPNLPF-1791 adding mainloop type check

2022-09-27 12:21 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            HTTPRequestAction.run(user, text_preprocessing_result, params)
HTTPRequestAction надо сначала инициализировать перед запуском, надо сделать HTTPRequestAction() и передать нужные параметры

2022-09-27 12:28 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            HTTPRequestAction.run(user, text_preprocessing_result, params)
Параметры надо передавать, когда они отрендерены, то есть отработала Jinja. Поэтому надо перенести вызов после `requests_data = self._render_request_data(params)`

2022-09-27 12:29 UTC, SyrexMinus requested changes
оставил комменты

2022-09-27 15:51 UTC, DimaProskurin commented
Ребят, тут две логики работы засунуто в один класс. На мой взгляд это не очень

Может попробуем разнести логику http и kafka в 2 разных класса actions? Или же сильно исправить этот класс PushAction чтобы через конструктор класса указывать - это работа через http или через kafka 

Автоматически завязываться на тип MainLoop это тоже что-то интересное, но выглядит костылем. Есть примеры Actions где по типу MainLoop определяется логика?

Имхо, явное лучше неявного, поэтому где юзеру надо http push action пусть юзает его, а где надо через kafka пусть явно пишет kafka push action

2022-09-27 15:52 UTC, DimaProskurin requested changes
оставил коммент выше

2022-10-25 12:07 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +
```suggestion
```

2022-10-25 19:58 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    """
```suggestion
    """ Action для получения токена в сервис пушей через http.
```

2022-10-25 20:00 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    Action для получения токена в сервис пушей через http.
```suggestion

```

2022-10-25 20:03 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.scope = items.get("scope")
```suggestion
        self.scope = items["scope"]
```
Поле обязательное

2022-10-25 20:09 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "scope": self.scope
Поле "scope" всегда должно иметь значение "SMART_PUSH", можно захардкодить

2022-10-25 20:25 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.http_request_action.run(user, text_preprocessing_result, params)
Поле RqUID генерируется всегда одинаково, можно его внутри акшна генерить

2022-10-25 20:28 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.http_request_action.run(user, text_preprocessing_result, params)
Я бы ещё сделал для удобство использования генерацию поля Authorization тоже внутри, прося от пользователя в items только client_id и client_secret.

2022-10-25 20:29 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    Ссылка на документацию с примерами получения токена:
Хорошо было бы добавить описание требуемых для заполнения в items полей и пример

2022-10-25 20:39 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.http_request_action = HTTPRequestAction(items, id)
Думаю, стоит задать дефолтное значение items["store"] для сохранения ответа

2022-10-25 21:01 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    """
""" Action для отправки пуш уведомлений в SmartPush API через http.

2022-10-25 21:01 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    Action для отправки пуш уведомлений в сервис пушей через http.
```suggestion
   
```

2022-10-25 21:52 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.templateContent = json.loads(json.dumps(items.get("templateContent")))
Для чего делается json.loads(json.dumps())?

2022-10-25 21:52 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.payload = json.loads(json.dumps(items.get("payload")))
Для чего делается json.loads(json.dumps())?

2022-10-25 21:54 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.templateContent = json.loads(json.dumps(items.get("templateContent")))
В этом объекте есть поля, которые можно заполнить без помощи разработчика? Если да, то будет удобнее, если мы сделаем это за него.

2022-10-25 21:55 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.payload = json.loads(json.dumps(items.get("payload")))
Тут некоторые поля точно можно заполнить кодом, например, projectId.

2022-10-25 21:57 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +                "protocolVersion": "protocolVersion",
Кажется, тут недопивало

2022-10-25 22:01 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.http_request_action.run(user, text_preprocessing_result, params)
Заголовки надо ещё отправлять

2022-10-25 22:01 UTC, SyrexMinus requested changes
Оставил комменты

2022-10-26 14:45 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +    """
Это коммент про форматирование, что в первой строке с кавычками идет краткое описание класса, а после пустой строки - детали (см. PEP8).

2022-10-26 15:00 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        items["store"] = DEFAULT_NAME_STORE
Здесь точно строгое переопределение должно быть?

2022-10-26 15:01 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +     - Аутентификация (получение токена): https://developers.sber.ru/docs/ru/va/how-to/app-support/smartpush/access
Думаю, будет полезно добавить куда результат запроса сохраняется

2022-10-26 15:11 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        request_body_parameters = {
Комментарий для красоты. Это можно вынести в init, чтобы не патчить уже инициализированный HTTP action.

2022-10-26 15:24 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "surface": "COMPANION", // опциональный параметр, по дефолту "COMPANION", без шаблонной генерации
Было бы удобнее, если бы все шаблонилось

2022-10-26 17:50 UTC, DenisSivko commented on core/basic_models/actions/push_action.py
> +        items["store"] = DEFAULT_NAME_STORE
Да, изначально этой переменной вообще нет в items. Из items достается store в HTTPRequestAction на 47 строке. А потом в методе process_result сетится в self.store дата в формате response.json()

2022-10-26 17:51 UTC, DenisSivko commented on core/basic_models/actions/push_action.py
> +        items["store"] = DEFAULT_NAME_STORE
То есть store в любом случае переопределится

2022-11-16 17:38 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "behavior": "some_behavior" // опциональный параметр
```suggestion
            "behavior": "some_behavior" // опциональный параметр, по дефолту "common_behavior"
```

2022-11-16 17:38 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "behavior": "some_behavior", // опциональный параметр
```suggestion
            "behavior": "some_behavior", // опциональный параметр, по дефолту common_behavior
```

2022-11-16 17:38 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "behavior": "some_behavior", // опциональный параметр
```suggestion
            "behavior": "some_behavior", // опциональный параметр, по дефолту "common_behavior"
```

2022-11-16 17:40 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +        self.headers["callbackUrl"] = items.get("callbackUrl")
```suggestion
        if items.get("callbackUrl")
            self.headers["callbackUrl"] = items["callbackUrl"]
```

2022-11-16 17:53 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +                "surface": self.surface,
Вот это поле должно быть на усмотрение разработчика. Он не всегда будет хотеть отправлять пуш на то же устройство, с которым прямо сейчас общается пользователь :)

2022-11-16 17:55 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.surface = items["surface"]
общее поле и для обоих типов реквестов, можно вынести из ифа.

2022-11-16 17:59 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.protocolVersion = items["protocolVersion"]
Судя по названию, версия протокола должна быть захардкожена. Мы реализуем в коде схему именно "V1" протокола.

2022-11-16 18:01 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.messageId = items["messageId"]
Это должно быть вытянуто из user.message.incremental_id

2022-11-16 18:02 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +                "messageName": self.messageName,
```suggestion
                "messageName": "SEND_PUSH",
```

2022-11-16 18:08 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.deliveryConfig = self.payload["deliveryConfig"] = {}
Зачем это затирается пустым диктом?

2022-11-16 18:11 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.deliveryConfig = self.payload["deliveryConfig"] = {}
Мб стоило просто прочитать deliveryConfig и целиком передать в том виде, который написал разраб?

2022-11-16 18:13 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            self.recipient = self.payload["recipient"] = {}
https://github.com/salute-developers/smart_app_framework/pull/55/files#r1024342977

2022-11-16 18:25 UTC, SyrexMinus requested changes
оставил комменты

2022-11-16 21:15 UTC, DenisSivko commented on core/basic_models/actions/push_action.py
> +        self.headers["callbackUrl"] = items.get("callbackUrl")
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/80362549/202295748-8627b303-35d7-45b8-a9d3-5378ead7fcc3.png">
сейчас так и работает. если callbackUrl = None, то в request_parameters это все равно не попадет

2022-11-25 16:10 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "type": "get_runtime_permissions"
Добавить behavior

2022-11-25 16:13 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "type": "get_runtime_permissions"
А ещё надо добавить в main_loop пояснение к ошибки про > commands, что это может возникать из-за сочетания ANSWER_TO_USER и другой команды, например GET_RUNTIME_PERMISSIONS

2022-11-25 16:15 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "type": "get_runtime_permissions"
И, по-хорошему, надо бы сделать систематический фикс этой проблемы через автоматическую остановку перед акшном, который продьюсит вторую команду

2022-11-25 16:27 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "surface": "{{message.device.surface}}", // обязательный параметр.
```suggestion
            "surface": "COMPANION", // обязательный параметр.
```

2022-11-25 16:27 UTC, SyrexMinus commented on core/basic_models/actions/push_action.py
> +            "access_token": "eyJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiYWxnIjoiUVAtMjU2In0", // обязательный параметр (получить можно через PushAuthenticationActionHttp)
```suggestion
            "access_token": "{{variables.push_authentification_response.access_token}}", // обязательный параметр (получить можно через PushAuthenticationActionHttp)
```

2022-11-25 16:35 UTC, SyrexMinus commented on smart_kit/handlers/handler_take_profile_data.py
> +
```suggestion
```

Я забыл убрать

2022-11-25 16:42 UTC, SyrexMinus requested changes
Осталось дополнить докстрингу behavior'ом, добавить лог в мейн луп и влить пару саджестов

2022-11-25 16:47 UTC, SyrexMinus commented
А ещё тесты падают

2022-11-27 19:55 UTC, SyrexMinus approved these changes

2022-11-27 19:56 UTC, merged