Remove log headers
salute-developers/smart_app_framework pull request #56
Opened 2022-09-29 02:28 UTC by sharifullinildus

Убрал хедеры из логов. Остаются лишь в ДП

2022-09-30 07:55 UTC, sharifullinildus commented
На исправлении

2022-10-24 13:34 UTC, DimaProskurin requested changes
Я не уверен, что мы одинаково поняли эту задачу. 
В задаче пишут "в лог откидываются значения хедеров в поле args.headers
необходимо убрать ненужные хедеры из лога"
Как я понял эту задачу, то
1) понять в каком месте происходит логгирование. Это все места где в log_params передается поле "headers"
2) выяснить какие хедеры являются ненужными; какие ключи хедеров в каких конкретно местах логгирования являются лишними. Для разных мест логгирования это могут быть разные списки "ненужных" хедеров
3) Убирать ненужные хедеры в логгировании на стороне DialogPolicy, а не на стороне фреймворка поскольку эта задача его не касается вроде бы

2022-10-31 17:28 UTC, DimaProskurin requested changes
Плюс было бы неплохо, чтобы у нас везде хедеры передавались либо только списком, либо только словарем. Как-то это унифицировать, поискать где они начинают разъезжаться по типам

2022-10-31 17:28 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +        params = cls.filter_headers(params)
Кажется, что сейчас везде в params["headers"] лежит строка
Необходимо это исправить, т.к. ты не можешь работать со строкой.

2022-11-01 07:43 UTC, sharifullinildus commented on core/logging/logger_utils.py
> +        params = cls.filter_headers(params)
Там внутри проверка, в случае строки мы ничего не сможем и не будем делать.

2022-11-01 07:47 UTC, sharifullinildus commented on core/logging/logger_utils.py
> +                params = {k: v for k, v in params[HEADERS].items() if v in cls.LOGGER_HEADERS}
Мы не всегда можем отфильтровать поля, поэтому чтобы не пложить строки return, я сохраняю имя params

2022-11-01 11:36 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +        params = cls.filter_headers(params)
В таком случае эта доработка будет бесполезна

2022-11-01 11:36 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +        params = cls.filter_headers(params)
Поскольку не будет решать поставленную задачу

2022-11-01 11:42 UTC, DimaProskurin requested changes

2022-11-01 11:42 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +    def filter_headers(cls, params: dict):
нету тайпинга на возвращаемое значение

2022-11-01 11:42 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +                params = {key: v for key, v in params[HEADERS].items() if key in cls.LOGGER_HEADERS}
либо k, v 
либо key, value

key, v -- неконсистенто

2022-11-01 11:42 UTC, DimaProskurin commented on core/logging/logger_utils.py
> +            elif isinstance(params[HEADERS], (list, tuple)):
может ли params[HEADERS] быть типом tuple?
Я такого не видел. Видел список, а вот тупла нет. Ты видел tuple?

2022-11-09 08:43 UTC, sharifullinildus commented on core/logging/logger_utils.py
> +            elif isinstance(params[HEADERS], (list, tuple)):
Все замечания исправлены

2022-11-09 09:26 UTC, DimaProskurin approved these changes

2022-11-10 07:41 UTC, merged