Add log_size to logger fields
salute-developers/smart_app_framework pull request #58
Opened 2022-09-30 04:38 UTC by sharifullinildus

2022-10-21 11:19 UTC, DimaProskurin requested changes
Ты это тестировал? Это работает?
Я не нашел использование класса BaseJsonFormatter нигде в коде, кроме как его определение в этом файле

2022-10-25 11:59 UTC, sharifullinildus commented
> Да, не в тот форматер добавлено было, перенес в SmartKitJsonFormatter, используемый для ДП

2022-10-26 15:17 UTC, DimaProskurin reviewed
Оставил коммент. Ты это запускал? Это работает как нужно?

2022-10-26 15:17 UTC, DimaProskurin commented on smart_kit/utils/logger_writer/logger_formatter.py
> +        return f'{result[:-1]},"log_size":{log_size}}}'
Почему здесь result обрезается до предпоследнего элемента?

2022-10-31 11:59 UTC, sharifullinildus commented on smart_kit/utils/logger_writer/logger_formatter.py
> +        return f'{result[:-1]},"log_size":{log_size}}}'
Мы слгека костыльно добавляем в уже сделанный джсон еще одно поле с размером этого джсона, поэтому вместо последней закрывающей скобки добавляем еще поле и закрываем скобки

2022-10-31 16:16 UTC, DimaProskurin requested changes

2022-10-31 16:16 UTC, DimaProskurin commented on smart_kit/utils/logger_writer/logger_formatter.py
> +        return f'{result[:-1]},"log_size":{log_size}}}'
Добавь пожалуйста комментарий в код, что в result хранится json строка. Мы делаем `[:-1]` поскольку хотим отрезать закрывающую фигурную скобку в json строке и добавить еще одно поле. Делаем так, чтобы не использовать дорогие методы json.loads, json.dumps на каждую запись в лог

2022-10-31 16:16 UTC, DimaProskurin commented on smart_kit/utils/logger_writer/logger_formatter.py
>  import time
Нужно удалить `import time` поскольку этот модуль нигде не используется в коде

2022-10-31 16:18 UTC, DimaProskurin commented on smart_kit/utils/logger_writer/logger_formatter.py
> +        return f'{result[:-1]},"log_size":{log_size}}}'
И еще ты не ответил на вопрос)
Ты это запускал? Это работает как надо?
Ты можешь создать тестовый апп с помощью фреймворка и посмотреть как там выглядят логи

2022-11-01 07:38 UTC, sharifullinildus commented on smart_kit/utils/logger_writer/logger_formatter.py
>  import time
Убрал, работу метода протестировал.

2022-11-01 11:34 UTC, DimaProskurin approved these changes

2022-11-01 11:48 UTC, merged