Убрал дублирующийся ниже лог
salute-developers/smart_app_framework pull request #59
Opened 2022-10-06 06:43 UTC by sharifullinildus

2022-10-21 09:29 UTC, DimaProskurin commented on scenarios/behaviors/behaviors.py
>          if callback:
В задаче просят "писать только одну запись: найден или нет подходящий callback".
В текущей реализации, если подходящий callback не найден, то в лог ничего не напишут.
Необходимо доделать логику, что если подходящий callback не найден, то писать об этом сообщение в лог

2022-10-24 13:22 UTC, DimaProskurin requested changes
Да, теперь сделано отлично для метода success. 

Предлагаю сделать аналогичный подход для методов fail, timeout, misstate, чтобы все было согласовано

2022-10-25 12:10 UTC, sharifullinildus commented
> Да, теперь сделано отлично для метода success.
> 
> Предлагаю сделать аналогичный подход для методов fail, timeout, misstate, чтобы все было согласовано

Сделано

2022-10-26 15:03 UTC, DimaProskurin requested changes
В методах fail, timeout, misstate ты забыл убрать лишний лог в начале метода, который 
```
log(f"behavior.fail started: got callback %({log_const.BEHAVIOR_CALLBACK_ID_VALUE})s.",
```

2022-10-31 16:07 UTC, DimaProskurin approved these changes

2022-11-01 07:36 UTC, merged