Feature/smartpay_action
salute-developers/smart_app_framework pull request #7
Opened 2022-04-27 07:58 UTC by Dan1lD

2022-05-05 07:30 UTC, SyrexMinus commented
Если текст, который отправится к тех. пису, - это описание к ПРу, то заставлять его смотреть код  - не очень хорошая идея, лучше вынести в описание в таком случае.

2022-05-05 08:45 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 08:46 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 08:48 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +    """
Можно сделать доку чуть полнее, если добавить в первую строчку краткое описание что делает акшн. Если внесёшь, отформатируй по PEP8.

2022-05-05 08:49 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +    """
См. коммент к SmartPayCreateAction

2022-05-05 08:50 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // обязательноый параметр
```suggestion
            "smartpay_params": { // обязательный параметр
```

2022-05-05 08:50 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // обязательноый параметр
Все ли параметры внутри параметров обязательные?

2022-05-05 08:52 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // обязательынй параметр
```suggestion
            "smartpay_params": { // обязательный параметр
```

2022-05-05 08:53 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // обязательынй параметр
Смотри коммент к тому же полю в SmartPayCreateAction

2022-05-05 08:55 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 08:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 08:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 08:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 09:01 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +    """
Смотри коммент к SmartPayCreateAction

2022-05-05 09:07 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 09:07 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 09:24 UTC, SyrexMinus commented on tests/core_tests/basic_scenario_models_test/action_test/test_smartpay.py
> +                                        "value": "Å\u001e13622200005881"
Спецсимволы лучше убрать, а то локально может падать тест

2022-05-05 15:50 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            del items["wait"]
Без del тоже работает

2022-05-05 15:55 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_create_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:55 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_perform_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:55 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_get_status_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:55 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_confirm_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_delete_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +        self.store = "smartpay_refund_answer"
Добавь в доку куда сохраняется ответ, плюс было бы неплохо, чтобы это поле можно было кастомно задавать.

2022-05-05 15:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 15:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 15:56 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +
```suggestion
```

2022-05-05 15:57 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +    """
Смотри коммент к SmartPayCreateAction

2022-05-05 15:57 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +    """
Смотри коммент к SmartPayCreateAction

2022-05-05 15:59 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // опциональный параметр, задаётся для неполной суммы (см. доку SmartPay API)
```suggestion
            "smartpay_params": { // опциональный параметр, задаётся для неполной суммы (см. документацию SmartPay API)
```

2022-05-05 16:00 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "smartpay_params": { // опциональный параметр, задаётся при частичном возврате (см. доку SmartPay API)
```suggestion
            "smartpay_params": { // опциональный параметр, задаётся при частичном возврате (см. документацию SmartPay API)
```

2022-05-05 16:01 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "behavior": "my_behavior", // обязательынй параметр
```suggestion
            "behavior": "my_behavior", // обязательный параметр
```

2022-05-05 16:01 UTC, SyrexMinus commented on core/basic_models/actions/smartpay.py
> +            "invoice_id": "0" // обязательынй параметр
```suggestion
            "invoice_id": "0" // обязательный параметр
```

2022-05-05 18:29 UTC, SyrexMinus requested changes
Поправь файлы доки, убери del, поправь тестик и можешь сделать self.store кастомные

2022-05-16 07:24 UTC, SyrexMinus approved these changes

2022-05-19 12:07 UTC, bart0003 approved these changes

2022-05-19 12:27 UTC, merged